"""Structured conversational decision schema and validation logic.

Defines the structured output contract expected from Gemini 3.5 Flash,
distinguishing proposed actions, grounding queries, and stage advancements.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field, field_validator

from src.core.errors import DecisionValidationError
from src.core.types import ConversationStage, DomainType
from src.domains.base import DomainConfig
from src.domains.registry import DomainRegistry, get_domain_registry


class ProposedAction(BaseModel):
    """Specification of an external tool action proposed by the LLM."""

    model_config = ConfigDict(extra="ignore")

    tool_name: str = Field(..., min_length=1, description="Registered identifier of the MCP tool")
    arguments: Dict[str, Any] = Field(
        default_factory=dict,
        description="Structured arguments prepared for the proposed tool invocation",
    )
    rationale: Optional[str] = Field(
        default=None,
        description="Reasoning why this action is being proposed at this conversational turn",
    )


class ConversationalDecision(BaseModel):
    """Structured turn decision generated by the LLM."""

    model_config = ConfigDict(extra="ignore")

    detected_domain: DomainType = Field(
        ...,
        description="Business domain identified from caller's latest utterance",
    )
    detected_intent: Optional[str] = Field(
        default=None,
        description="Specific intent classified for this turn",
    )
    detected_sub_intent: Optional[str] = Field(
        default=None,
        description="Sub-intent or specialization if applicable",
    )
    extracted_slots: Dict[str, Any] = Field(
        default_factory=dict,
        description="Entity values extracted from current utterance or dialogue",
    )
    proposed_stage: ConversationStage = Field(
        default=ConversationStage.INFORMATION,
        description="Recommended conversation stage progression",
    )
    user_facing_response: str = Field(
        ...,
        min_length=1,
        description="Natural conversational utterance to be voiced to the caller",
    )
    knowledge_required: bool = Field(
        default=False,
        description="True if factual grounding is needed from the domain knowledge base (RAG)",
    )
    knowledge_query: Optional[str] = Field(
        default=None,
        description="Semantic search query text for RAG retrieval if knowledge is required",
    )
    action_proposed: bool = Field(
        default=False,
        description="True if an external mutation action is proposed (email, calendar, CRM, etc.)",
    )
    proposed_action: Optional[ProposedAction] = Field(
        default=None,
        description="Details of proposed action; MUST NOT be treated as already executed",
    )
    needs_clarification: bool = Field(
        default=False,
        description="True if caller's intent was ambiguous or underspecified",
    )
    clarification_question: Optional[str] = Field(
        default=None,
        description="Clarification question to ask caller if needs_clarification is True",
    )
    suggested_termination: bool = Field(
        default=False,
        description="Advisory signal from LLM; must still pass explicit termination validation",
    )

    @field_validator("detected_domain", mode="before")
    @classmethod
    def normalize_domain(cls, v: Any) -> Any:
        if isinstance(v, str):
            clean = v.strip().lower()
            if "edusaas" in clean:
                return DomainType.EDUSAAS
            if "vayvora" in clean:
                return DomainType.VAYVORA
            return DomainType.GENERAL
        return v

    @field_validator("proposed_stage", mode="before")
    @classmethod
    def normalize_stage(cls, v: Any) -> Any:
        if isinstance(v, str):
            clean = v.strip().lower()
            try:
                return ConversationStage(clean)
            except ValueError:
                return ConversationStage.INFORMATION
        return v

    @field_validator("proposed_action", mode="before")
    @classmethod
    def normalize_proposed_action(cls, v: Any) -> Any:
        if not v or v == "null" or v == "":
            return None
        return v


class DecisionValidator:
    """Validates ConversationalDecision instances against domain rules and registries."""

    def __init__(self, registry: Optional[DomainRegistry] = None) -> None:
        self.registry = registry or get_domain_registry()

    def validate_and_filter(
        self, decision: ConversationalDecision
    ) -> ConversationalDecision:
        """Validate decision fields, sanitize slots, and return verified decision."""
        # 1. Validate Domain
        domain_config = self.registry.get(decision.detected_domain)
        if not domain_config:
            raise DecisionValidationError(
                f"Unknown domain detected: '{decision.detected_domain}'"
            )

        # 2. Validate Intent (if provided)
        if decision.detected_intent:
            intent_clean = decision.detected_intent.strip().lower()
            if not domain_config.is_intent_supported(intent_clean):
                # Check if it belongs to another domain or fallback
                # If unsupported in current domain, flag as general or keep raw intent
                pass

        # 3. Validate & Filter Slots
        sanitized_slots: Dict[str, Any] = {}
        allowed_slot_names = set(domain_config.get_slot_names())
        # Universal caller slots are always allowed
        universal_slots = {"name", "student_name", "contact_name", "email", "phone", "company", "company_name"}

        for key, val in decision.extracted_slots.items():
            k_clean = key.strip().lower()
            if k_clean in allowed_slot_names or k_clean in universal_slots:
                if val is not None and str(val).strip():
                    sanitized_slots[k_clean] = val

        # 4. Action Validation & Normalization
        if decision.proposed_action:
            tool_name = decision.proposed_action.tool_name.strip()
            if tool_name == "connect_advisor":
                phone = (
                    decision.proposed_action.arguments.get("phone")
                    or sanitized_slots.get("phone")
                )
                name = (
                    decision.proposed_action.arguments.get("name")
                    or sanitized_slots.get("name")
                    or sanitized_slots.get("contact_name")
                    or sanitized_slots.get("student_name")
                    or "Caller"
                )
                if phone:
                    decision.proposed_action.tool_name = "create_hr_followup"
                    decision.proposed_action.arguments = {
                        "candidate_name": name,
                        "phone": phone,
                        "notes": decision.proposed_action.arguments.get("notes") or "Advisor connection callback requested",
                    }
                    decision.action_proposed = True
                else:
                    decision.proposed_action = None
                    decision.action_proposed = False
            else:
                decision.action_proposed = True
        elif decision.action_proposed and not decision.proposed_action:
            decision.action_proposed = False

        # 5. Knowledge query consistency
        if decision.knowledge_required and not decision.knowledge_query:
            # Default query to user facing response or intent
            decision.knowledge_query = decision.detected_intent or "general inquiry"

        decision.extracted_slots = sanitized_slots
        return decision
