from typing import Any

from langgraph.graph import END, START, StateGraph

from src.agents.edges.routing import (
    route_after_llm_router,
    route_after_memory,
    route_after_rag,
<<<<<<< HEAD
    route_after_tool
=======
    route_after_tool,
>>>>>>> 734eed0 (Implement hybrid LLM router)
)
from src.agents.nodes.llm_node import LLMNode
from src.agents.nodes.llm_router_node import LLMRouterNode
from src.agents.nodes.memory_node import MemoryNode
from src.agents.nodes.rag_node import RAGNode
from src.agents.nodes.response_node import ResponseNode
from src.agents.nodes.tool_node import ToolNode
from src.agents.state import AgentState


class AgentGraph:
    """
    Main Vayvora AI Agent orchestration graph.

    Architecture:

        User Input
            ↓
        LLM Router
            ↓
        ┌───────┼───────┐
        ↓       ↓       ↓
       LLM     RAG     MCP
        ↓       ↓       ↓
        │       │       │
        │       └──→ LLM
        │
        └──────────────→ Final Answer

    The LLM Router is always the first decision-making node.

    Final routes:
        llm
        rag
        mcp

    RAG and MCP never generate the final response.
    The final response is always generated by LLMNode.
    """

    def _init_(
        self,
        llm: Any,
        tool_registry: Any = None,
        memory_store: Any = None,
        retriever: Any = None,
    ) -> None:

        # -----------------------------------------------------
        # LLM Router
        # -----------------------------------------------------

        self.llm_router_node = LLMRouterNode(
            llm=llm
        )

        # -----------------------------------------------------
        # Memory
        # -----------------------------------------------------

        self.memory_node = MemoryNode(
            memory_store=memory_store
        )

        # -----------------------------------------------------
        # RAG
        # -----------------------------------------------------

        self.rag_node = RAGNode(
            retriever=retriever
        )

        # -----------------------------------------------------
        # MCP / Tools
        # -----------------------------------------------------

        self.tool_node = ToolNode(
            tool_registry=tool_registry
        )

        # -----------------------------------------------------
        # Final LLM
        # -----------------------------------------------------

        self.llm_node = LLMNode(
            llm=llm
        )

        # -----------------------------------------------------
        # Final response preparation
        # -----------------------------------------------------

        self.response_node = ResponseNode()

        # -----------------------------------------------------
        # Build graph
        # -----------------------------------------------------

        self.graph = self._build_graph()

    # =========================================================
    # BUILD GRAPH
    # =========================================================

    def _build_graph(self):
        workflow = StateGraph(AgentState)

        # -----------------------------------------------------
        # Nodes
        # -----------------------------------------------------

        workflow.add_node(
            "llm_router",
            self.llm_router_node.run,
        )

        workflow.add_node(
            "memory",
            self.memory_node.run,
        )

        workflow.add_node(
            "rag",
            self.rag_node.run,
        )

        workflow.add_node(
            "tool",
            self.tool_node.run,
        )

        workflow.add_node(
            "llm",
            self.llm_node.run,
        )

        workflow.add_node(
            "response",
            self.response_node.run,
        )

        # -----------------------------------------------------
        # START → LLM Router
        # -----------------------------------------------------

        workflow.add_edge(
            START,
            "llm_router",
        )

        # -----------------------------------------------------
        # LLM Router
        # -----------------------------------------------------

        workflow.add_conditional_edges(
            "llm_router",
            route_after_llm_router,
            {
                "llm": "llm",
                "rag": "memory",
                "tool": "memory",
            },
        )

        # -----------------------------------------------------
        # Memory
        # -----------------------------------------------------

        workflow.add_conditional_edges(
            "memory",
            route_after_memory,
            {
                "llm": "llm",
                "rag": "rag",
                "tool": "tool",
            },
        )

        # -----------------------------------------------------
        # RAG → Final LLM
        # -----------------------------------------------------

        workflow.add_conditional_edges(
            "rag",
            route_after_rag,
            {
                "llm": "llm",
            },
        )

        # -----------------------------------------------------
        # MCP → Final LLM
        # -----------------------------------------------------

        workflow.add_conditional_edges(
            "tool",
            route_after_tool,
            {
                "llm": "llm",
            },
        )

        # -----------------------------------------------------
        # Final LLM → Response
        # -----------------------------------------------------

        workflow.add_edge(
            "llm",
            "response",
        )

        # -----------------------------------------------------
        # Response → END
        # -----------------------------------------------------

        workflow.add_edge(
            "response",
            END,
        )

        return workflow.compile()